# Generated by Django 3.2.8 on 2021-11-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20211108_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'ToDo заметка', 'verbose_name_plural': 'ToDo заметки'},
        ),
    ]
