# Generated by Django 3.2.8 on 2021-11-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_auto_20211108_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_to_repo',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
