# Generated by Django 3.2.8 on 2021-11-29 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0009_alter_todo_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user_created',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='todo_user_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
